### ISSUE TITLE
[B-Scope] Something wrong with the fine Z motor

### ISSUE THREAD

**Issue by mkrumin** [mkrumin/2p-rigs#1]
Federico, please write a description?

**Comment by synapticlee** [comment]
(Low priority). The menu-based "jumping" between preset z locations no longer works. As in, nothing happens when you try to jump to 21000 or 3000 or whatever. Scrolling up and down (by manually rotating the dial) still works but is tedious. Using the software b-scope controls works 75% of the time but is also a bit tedious and sometimes doesn't work. Federico said this happened before?

**Comment by lfedros** [comment]
It's not just the 'go to marked position' command that does not work. The motor also shows signs of malfunction that I think will require maintenance. Specifically, around the positions that we use the most (maybe it is a matter of some mechanism wearing down), namely between 2 and 3 mm, the stepper is jittery and does not respond well to wheel movements, and sometimes it get stuck in one position and does not go further in one direction.

**Comment by synapticlee** [comment]
> Specifically, around the positions that we use the most (maybe it is a matter of some mechanism wearing down), namely between 2 and 3 mm, the stepper is jittery and does not respond well to wheel movements, and sometimes it get stuck in one position and does not go further in one direction.

I haven't experienced that myself but I've only been using it for a couple days

**Comment by mkrumin** [comment]
Diego managed to fix the fine Z motor. 
There was a problem with the optical encoder reading the position (the small magnet, which is marking the movement range limits got unglued and was sitting in the middle of where the encoder is supposed to read the stripes), and because it was having crap readings the system was aborting any automatic movement immediately. Should be working fine now.
